version: '3.4'

x-inputs: &inputs
  PREFIX: 'Xi'
  BNABS: '3BNC117,10-1074'
  MODELS: 'GBM,RF,LBUM'
  NON_ALIGNED_ENV_FASTA: 'Xi_envs.fasta'
  REGRESSION: 'true'
  COMBINATION: 'false'

x-inputs-volume: &inputs-volume
  type: bind
  source: ./inputs
  target: /home/inputs

x-outputs-volume: &outputs-volume
  type: bind
  source: ./outputs
  target: /home/outputs

services:
  PREPROCESS:
    image: lbum_preprocess:1.0
    environment: 
      <<: *inputs
    volumes:
     - <<: *inputs-volume
     - <<: *outputs-volume

  MAFFT:
    image: lbum_mafft:1.0
    environment:
      <<: *inputs
    volumes:
     - <<: *inputs-volume
     - <<: *outputs-volume

  MODELS:
    image: lbum:1.0
    environment:
      <<: *inputs
    volumes:
     - <<: *inputs-volume
     - <<: *outputs-volume